<html> 
 
<head> 
  <title>NLP project web interface</title> 
</head> 
 
<body style="margin: 0; padding: 0"> 
 
<table width="728" 
           cellspacing="0" 
           cellpadding="0"
           style="padding: 0; margin: 0; border-collapse: collapse"> 
<tr style="padding: 0; margin: 0"> 
<td width="728" 
       colspan="2" 
       style="padding: 0; margin: 0"><img 
          src="background.png" 
          style="padding: 0; margin"></td> 
</tr> 
<tr style="padding: 0; margin: 0"> 
<td width="728" 
       colspan="2" 
       style="padding: 0; margin: 0"><div 
         style="padding: 0; 
                    margin: 0; 
                    text-align: center;
                    font-size: small; 
                    background-color: #99CCCC"> 
       Application for cleaning extracted data from news articles
</div></td> 
</tr> 
<tr> 
    <td rowspan="2" 
           width="240"
           valign="top"> 
       <div style="height: 500px; padding: 20px; border-right: 3px dashed; margin-right: 20px"> 
			<input type="submit" name="submit" value="Submit"> <br/> 
            <input type="button" name="next" value="Next"> <br/> 
            <input type="button" name="finish" value="Finish">  <br/> 
       </div> 
    </td> 
    <td width="488"> 
         <div style="margin-top: 12px; margin-bottom: 12 px"> 

    